FactoryGirl.define do
  factory :otg_sess do
    target_id 1
one_id "MyString"
one_description "MyString"
one_findings "MyString"
one_liklihood 1
one_consequence 1
one_risk 1
one_recommendations "MyString"
one_current false
two_id "MyString"
two_description "MyString"
two_findings "MyString"
two_liklihood 1
two_consequence 1
two_risk 1
two_recommendations "MyString"
two_current false
three_id "MyString"
three_description "MyString"
three_findings "MyString"
three_liklihood 1
three_consequence 1
three_risk 1
three_recommendations "MyString"
three_current false
four_id "MyString"
four_description "MyString"
four_findings "MyString"
four_liklihood 1
four_consequence 1
four_risk 1
four_recommendations "MyString"
four_current false
five_id "MyString"
five_description "MyString"
five_findings "MyString"
five_liklihood 1
five_consequence 1
five_risk 1
five_recommendations "MyString"
five_current false
six_id "MyString"
six_description "MyString"
six_findings "MyString"
six_liklihood 1
six_consequence 1
six_risk 1
six_recommendations "MyString"
six_current false
seven_id "MyString"
seven_description "MyString"
seven_findings "MyString"
seven_liklihood 1
seven_consequence 1
seven_risk 1
seven_recommendations "MyString"
seven_current false
eight_id "MyString"
eight_description "MyString"
eight_findings "MyString"
eight_liklihood 1
eight_consequence 1
eight_risk 1
eight_recommendations "MyString"
eight_current false
  end

end
