FactoryGirl.define do
  factory :otg_inpval do
    target_id 1
one_id "MyString"
one_description "MyString"
one_findings "MyString"
one_liklihood 1
one_consequence 1
one_risk 1
one_recommendations "MyString"
one_current false
two_id "MyString"
two_description "MyString"
two_findings "MyString"
two_liklihood 1
two_consequence 1
two_risk 1
two_recommendations "MyString"
two_current false
three_id "MyString"
three_description "MyString"
three_findings "MyString"
three_liklihood 1
three_consequence 1
three_risk 1
three_recommendations "MyString"
three_current false
four_id "MyString"
four_description "MyString"
four_findings "MyString"
four_liklihood 1
four_consequence 1
four_risk 1
four_recommendations "MyString"
four_current false
five_id "MyString"
five_description "MyString"
five_findings "MyString"
five_liklihood 1
five_consequence 1
five_risk 1
five_recommendations "MyString"
five_current false
six_id "MyString"
six_description "MyString"
six_findings "MyString"
six_liklihood 1
six_consequence 1
six_risk 1
six_recommendations "MyString"
six_current false
seven_id "MyString"
seven_description "MyString"
seven_findings "MyString"
seven_liklihood 1
seven_consequence 1
seven_risk 1
seven_recommendations "MyString"
seven_current false
eight_id "MyString"
eight_description "MyString"
eight_findings "MyString"
eight_liklihood 1
eight_consequence 1
eight_risk 1
eight_recommendations "MyString"
eight_current false
nine_id "MyString"
nine_description "MyString"
nine_findings "MyString"
nine_liklihood 1
nine_consequence 1
nine_risk 1
nine_recommendations "MyString"
nine_current false
ten_id "MyString"
ten_description "MyString"
ten_findings "MyString"
ten_liklihood 1
ten_consequence 1
ten_risk 1
ten_recommendations "MyString"
ten_current false
eleven_id "MyString"
eleven_description "MyString"
eleven_findings "MyString"
eleven_liklihood 1
eleven_consequence 1
eleven_risk 1
eleven_recommendations "MyString"
eleven_current false
ten_id "MyString"
twelve_description "MyString"
twelve_findings "MyString"
twelve_liklihood 1
twelve_consequence 1
twelve_risk 1
twelve_recommendations "MyString"
twelve_current false
thirteen_id "MyString"
thirteen_description "MyString"
thirteen_findings "MyString"
thirteen_liklihood 1
thirteen_consequence 1
thirteen_risk 1
thirteen_recommendations "MyString"
thirteen_current false
fourteen_id "MyString"
fourteen_description "MyString"
fourteen_findings "MyString"
fourteen_liklihood 1
fourteen_consequence 1
fourteen_risk 1
fourteen_recommendations "MyString"
fourteen_current false
fifteen_id "MyString"
fifteen_description "MyString"
fifteen_findings "MyString"
fifteen_liklihood 1
fifteen_consequence 1
fifteen_risk 1
fifteen_recommendations "MyString"
fifteen_current false
sixteen_id "MyString"
sixteen_description "MyString"
sixteen_findings "MyString"
sixteen_liklihood 1
sixteen_consequence 1
sixteen_risk 1
sixteen_recommendations "MyString"
sixteen_current false
seventeen_id "MyString"
seventeen_description "MyString"
seventeen_findings "MyString"
seventeen_liklihood 1
seventeen_consequence 1
seventeen_risk 1
seventeen_recommendations "MyString"
seventeen_current false
  end

end
