# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e0b7f14d8982267208f5c8e179b5b69c3e5cb08eeb3987e137b11e4402082d923418b80b6bbc8b27ee69c66cce6de39b541d40dcc5c5b0d2f9ffb4c54b155f

test:
  secret_key_base: 522e594fcb148877bfe47c21dba518c310eed4d255490008cce863386343df822c338ef86007d061b2157ab9b833efb6b4bd11fb94a0f02c9f1ee100a1ccf0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
