# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150401062418) do

  create_table "otg_authns", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.string   "nine_id"
    t.string   "nine_description"
    t.string   "nine_findings"
    t.integer  "nine_liklihood"
    t.integer  "nine_consequence"
    t.integer  "nine_risk"
    t.string   "nine_recommendations"
    t.boolean  "nine_current"
    t.string   "ten_id"
    t.string   "ten_description"
    t.string   "ten_findings"
    t.integer  "ten_liklihood"
    t.integer  "ten_consequence"
    t.integer  "ten_risk"
    t.string   "ten_recommendations"
    t.boolean  "ten_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_authzs", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_buslogics", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.string   "nine_id"
    t.string   "nine_description"
    t.string   "nine_findings"
    t.integer  "nine_liklihood"
    t.integer  "nine_consequence"
    t.integer  "nine_risk"
    t.string   "nine_recommendations"
    t.boolean  "nine_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_clients", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.string   "nine_id"
    t.string   "nine_description"
    t.string   "nine_findings"
    t.integer  "nine_liklihood"
    t.integer  "nine_consequence"
    t.integer  "nine_risk"
    t.string   "nine_recommendations"
    t.boolean  "nine_current"
    t.string   "ten_id"
    t.string   "ten_description"
    t.string   "ten_findings"
    t.integer  "ten_liklihood"
    t.integer  "ten_consequence"
    t.integer  "ten_risk"
    t.string   "ten_recommendations"
    t.boolean  "ten_current"
    t.string   "eleven_id"
    t.string   "eleven_description"
    t.string   "eleven_findings"
    t.integer  "eleven_liklihood"
    t.integer  "eleven_consequence"
    t.integer  "eleven_risk"
    t.string   "eleven_recommendations"
    t.boolean  "eleven_current"
    t.string   "twelve_description"
    t.string   "twelve_findings"
    t.integer  "twelve_liklihood"
    t.integer  "twelve_consequence"
    t.integer  "twelve_risk"
    t.string   "twelve_recommendations"
    t.boolean  "twelve_current"
    t.datetime "created_at",             null: false
    t.datetime "updated_at",             null: false
  end

  create_table "otg_configs", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_crypsts", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_errs", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
  end

  create_table "otg_idents", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_infos", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.string   "nine_id"
    t.string   "nine_description"
    t.string   "nine_findings"
    t.integer  "nine_liklihood"
    t.integer  "nine_consequence"
    t.integer  "nine_risk"
    t.string   "nine_recommendations"
    t.boolean  "nine_current"
    t.string   "ten_id"
    t.string   "ten_description"
    t.string   "ten_findings"
    t.integer  "ten_liklihood"
    t.integer  "ten_consequence"
    t.integer  "ten_risk"
    t.string   "ten_recommendations"
    t.boolean  "ten_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "otg_inpvals", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.string   "nine_id"
    t.string   "nine_description"
    t.string   "nine_findings"
    t.integer  "nine_liklihood"
    t.integer  "nine_consequence"
    t.integer  "nine_risk"
    t.string   "nine_recommendations"
    t.boolean  "nine_current"
    t.string   "ten_id"
    t.string   "ten_description"
    t.string   "ten_findings"
    t.integer  "ten_liklihood"
    t.integer  "ten_consequence"
    t.integer  "ten_risk"
    t.string   "ten_recommendations"
    t.boolean  "ten_current"
    t.string   "eleven_id"
    t.string   "eleven_description"
    t.string   "eleven_findings"
    t.integer  "eleven_liklihood"
    t.integer  "eleven_consequence"
    t.integer  "eleven_risk"
    t.string   "eleven_recommendations"
    t.boolean  "eleven_current"
    t.string   "twelve_description"
    t.string   "twelve_findings"
    t.integer  "twelve_liklihood"
    t.integer  "twelve_consequence"
    t.integer  "twelve_risk"
    t.string   "twelve_recommendations"
    t.boolean  "twelve_current"
    t.string   "thirteen_id"
    t.string   "thirteen_description"
    t.string   "thirteen_findings"
    t.integer  "thirteen_liklihood"
    t.integer  "thirteen_consequence"
    t.integer  "thirteen_risk"
    t.string   "thirteen_recommendations"
    t.boolean  "thirteen_current"
    t.string   "fourteen_id"
    t.string   "fourteen_description"
    t.string   "fourteen_findings"
    t.integer  "fourteen_liklihood"
    t.integer  "fourteen_consequence"
    t.integer  "fourteen_risk"
    t.string   "fourteen_recommendations"
    t.boolean  "fourteen_current"
    t.string   "fifteen_id"
    t.string   "fifteen_description"
    t.string   "fifteen_findings"
    t.integer  "fifteen_liklihood"
    t.integer  "fifteen_consequence"
    t.integer  "fifteen_risk"
    t.string   "fifteen_recommendations"
    t.boolean  "fifteen_current"
    t.string   "sixteen_id"
    t.string   "sixteen_description"
    t.string   "sixteen_findings"
    t.integer  "sixteen_liklihood"
    t.integer  "sixteen_consequence"
    t.integer  "sixteen_risk"
    t.string   "sixteen_recommendations"
    t.boolean  "sixteen_current"
    t.string   "seventeen_id"
    t.string   "seventeen_description"
    t.string   "seventeen_findings"
    t.integer  "seventeen_liklihood"
    t.integer  "seventeen_consequence"
    t.integer  "seventeen_risk"
    t.string   "seventeen_recommendations"
    t.boolean  "seventeen_current"
    t.datetime "created_at",                null: false
    t.datetime "updated_at",                null: false
  end

  create_table "otg_sesses", force: :cascade do |t|
    t.integer  "target_id"
    t.string   "one_id"
    t.string   "one_description"
    t.string   "one_findings"
    t.integer  "one_liklihood"
    t.integer  "one_consequence"
    t.integer  "one_risk"
    t.string   "one_recommendations"
    t.boolean  "one_current"
    t.string   "two_id"
    t.string   "two_description"
    t.string   "two_findings"
    t.integer  "two_liklihood"
    t.integer  "two_consequence"
    t.integer  "two_risk"
    t.string   "two_recommendations"
    t.boolean  "two_current"
    t.string   "three_id"
    t.string   "three_description"
    t.string   "three_findings"
    t.integer  "three_liklihood"
    t.integer  "three_consequence"
    t.integer  "three_risk"
    t.string   "three_recommendations"
    t.boolean  "three_current"
    t.string   "four_id"
    t.string   "four_description"
    t.string   "four_findings"
    t.integer  "four_liklihood"
    t.integer  "four_consequence"
    t.integer  "four_risk"
    t.string   "four_recommendations"
    t.boolean  "four_current"
    t.string   "five_id"
    t.string   "five_description"
    t.string   "five_findings"
    t.integer  "five_liklihood"
    t.integer  "five_consequence"
    t.integer  "five_risk"
    t.string   "five_recommendations"
    t.boolean  "five_current"
    t.string   "six_id"
    t.string   "six_description"
    t.string   "six_findings"
    t.integer  "six_liklihood"
    t.integer  "six_consequence"
    t.integer  "six_risk"
    t.string   "six_recommendations"
    t.boolean  "six_current"
    t.string   "seven_id"
    t.string   "seven_description"
    t.string   "seven_findings"
    t.integer  "seven_liklihood"
    t.integer  "seven_consequence"
    t.integer  "seven_risk"
    t.string   "seven_recommendations"
    t.boolean  "seven_current"
    t.string   "eight_id"
    t.string   "eight_description"
    t.string   "eight_findings"
    t.integer  "eight_liklihood"
    t.integer  "eight_consequence"
    t.integer  "eight_risk"
    t.string   "eight_recommendations"
    t.boolean  "eight_current"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "projects", force: :cascade do |t|
    t.string   "title"
    t.string   "description"
    t.string   "scope_document_name"
    t.string   "deliverables"
    t.integer  "effort_days"
    t.string   "tester_name"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
  end

  create_table "targets", force: :cascade do |t|
    t.string   "role"
    t.string   "hostname"
    t.string   "ip_address"
    t.string   "fqdn"
    t.integer  "project_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
